# Generated by Django 5.0.7 on 2024-08-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hologram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('superpower', models.CharField(max_length=100)),
                ('extinct_since', models.IntegerField()),
            ],
        ),
    ]
